name: Docker Image - Version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: luois45
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Luois45
          password: ${{ secrets.GIT_TOKEN }}

      - name: Extract Version Tag
        id: extract_tag
        run: echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            luois45/claim-free-steam-packages:${{ env.VERSION_TAG }}
            ghcr.io/luois45/claim-free-steam-packages:${{ env.VERSION_TAG }}
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7
